### ISSUE TITLE
实现车辆在库和出车API

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#125]

**Comment by AceBear** [comment]
使用以下查询,即可获取所有派遣未回的小队,结果中包含了所有人员和车辆
GET /fleet/:fleetId/dispatchTeam?recover_time=null

@Septemberwh 写一个测试用例,单独验证一下 recover_time=null 是否正常工作
这个查询应只返回recover_time is null的派遣小队
如果 @Septemberwh 验证正常,Close this issue.
