### ISSUE TITLE
获取车辆的最后一条地理位置信息

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#132]
建议和查询所有车辆数据一起查询出来

**Comment by AceBear** [comment]
组合实现
GET /fleet/:fleetId/vehicle/:vehicleId/trip?pageSize=1 获得最后一条Trip数据
GET /fleet/:fleetId/vehicle/:vehicleId/trip/:tripId/path?pageSize=1&sortBy=locationTime- 获得最后位置

**Comment by AceBear** [comment]
如果要获取车队所有车的当前位置,这个可以提供一个API 参见 #150
