### ISSUE TITLE
司机行程记录API

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#140]
1.一个司机的所有行程数据组合车牌号、驾驶人、品牌、车系（司机ID）

**Comment by AceBear** [comment]
- 我们可以从Vehicle查找对应的Trip
- 我们还需要从Staff查找对应的Trip
- 设计方案,使得从Staff查找对应的Trip成为可能
- 这需要一整套解决方案
- 包括可能需要增加 表,在biz-core中增加若干个方法,以及fleet中增加相应的API
