### ISSUE TITLE
远程检测时间存疑

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#151]
2次远程检测后
检测结果上显示的是前一次检测的时间
![9c3b9ccd7daadb5770fc228d8b5a0a24](https://cloud.githubusercontent.com/assets/5030312/6728877/30fb97ec-ce68-11e4-825b-03b67d1ca823.jpg)

**Comment by mqwangincar** [comment]
多次测试后发现，点击“远程检测”，会得到以下几种情况
1. 显示检测失败，且显示本次检测的时间，检测记录中无此次记录（正常）
2. 显示检测成功并返回检测结果，显示检测时间为上一次检测成功的时间，检测记录中无此次记录（不应该存在这种逻辑。 若成功则应显示本次的检测时间并在检测记录中形成一条记录；若失败应显示检测失败）
3. 显示检测成功并返回检测结果，显示检测时间为本次检测的时间，检测记录中增加此次记录（正常）

**Comment by AceBear** [comment]
原因:
1. 第1次,显示检测失败,但其实是检测结果超时,超时后成功了,结果在服务器内存里缓冲.
2. 紧接着第2次检测,检测请求还在短信中转中,还没有发到OBD,这时检查结果,其实取回的是上一次内存中缓冲的那个超时了的第1次的检查结果.
3. 第2次的结果又被缓冲到服务器内存中,会被下一次检测取到

**Comment by AceBear** [comment]
## 解决办法
- 向服务器申请远程检测时,服务器检查此OBD是否已经有客户端没有取回的结果,  
  如果有,则返回这个现成结果的序列号,否则产生一个新的序列号
  服务器需要返回序列号(或现成的,或新产生的)返回给客户端.  
  **如果使用了现成的序列号,则服务器并不实际在OBD执行远程检测  
  只有新产生的序列号,才执行真正的检测逻辑**
- 客户端凭OBD号+序列号获取远程检测结果
- 服务器内存中,只缓冲最后一次的结果.
- 服务器收到客户端请求结果时,比较序列号,如果比当前序列号小,返回错误:结果已被抛弃;~~如果比当前序列号大,返回错误:无效序列号~~.如果相等**或比当前序列号更大**,则执行先前的逻辑(WAIT或检查真正的结果)
- 一但向客户端返回了非WAIT的真正检查结果,清除结果缓冲.
- 服务器设置另一个超时器,用于抛弃客户端没有取回的检查结果

##### 即允许连续的相隔不久的远程检测请求共享1次检查结果

**Comment by AceBear** [comment]
## 解决办法简化
- 向服务器申请远程检测时,服务器检查此OBD是否已经有客户端没有取回的结果,  
  如果有,则直接返回,并不执行真正的检查逻辑  
  如果没有,则执行正真的检查逻辑
- 服务器内存中,只缓冲最后一次的结果.
- 一但向客户端返回了非WAIT的真正检查结果,清除结果缓冲.
- 服务器设置另一个超时器,用于抛弃客户端没有取回的检查结果,确保不会有太久之前的结果被返回

**Comment by mqwangincar** [comment]
![150322](https://cloud.githubusercontent.com/assets/9412266/6768564/fcca7f08-d0ae-11e4-817d-0033640ce712.jpg)

**Comment by AceBear** [comment]
已修正,刚刚发布
