### ISSUE TITLE
里程数应随OBD采集的数据变动

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#152]
里程数一直固定,没有随OBD行程增涨

**Comment by AceBear** [comment]
![82803d286d5a8e57215b7dbc7fa0152c](https://cloud.githubusercontent.com/assets/5030312/6726179/2062a628-ce4f-11e4-84d7-9c073d600bdc.jpg)

**Comment by AceBear** [comment]
原因:更换了OBD后,OBD里程计数仍然保持了旧OBD上的那个1776
我们当前的算法是从OBD表里取最大的那个里程数,做为OBD里程
![ikgpdb64kb lgied543zv35](https://cloud.githubusercontent.com/assets/5030312/6727159/482d897e-ce5a-11e4-9a0a-e8d789c2dad6.jpg)

**Comment by AceBear** [comment]
- 修正OBD里程计算方法
  原算法:取OBD行程表中,最mileage的最大值
  修正后算法:取OBD行程表中,最后一个点火时间记录的mileage值

``` SQL
SELECT mileage FROM t_obd_drive
WHERE obdcode = 'INCAR123456789' and mileage is not null
ORDER BY fireTime DESC LIMIT 1;
```
- 修改迁移OBD逻辑
  增加一个修正基准mileage的过程

```
新基准里程 = 旧基准里程 + 旧OBD里程 - 新OBD里程
```

**Comment by AceBear** [comment]
修改迁移OBD逻辑
增加一个修正基准mileage的过程

新基准里程 = 旧基准里程 + 旧OBD里程 - 新OBD里程

**Comment by mqwangincar** [comment]
修改更新到服务器了吗？我现在看到的界面中，下面这个计算是正确的
![screenshot_2015-03-19-23-05-39](https://cloud.githubusercontent.com/assets/9412266/6794186/96dcbbc8-d209-11e4-8b1d-93276934f861.jpeg)

**Comment by AceBear** [comment]
刚刚发布

**Comment by mqwangincar** [comment]
![screenshot_2015-03-24-13-46-01](https://cloud.githubusercontent.com/assets/9412266/6796331/3c510f60-d22c-11e4-92ca-f8de74575d56.jpeg)
这个地方没改？

**Comment by AceBear** [comment]
Fixed 我的信息里的里程算法.已发布.
