### ISSUE TITLE
轨迹记录里程数错误

### ISSUE THREAD

**Issue by mqwangincar** [InCar/Track#154]
场景：
1. 车辆在12:00自A点启动
2. 12:25，点击轨迹记录
3. 12:30，再次打开轨迹记录，界面内容显示开始记录，开始记录时间为12:25，行驶里程为24.564公里，轨迹为~12:25开始的行驶轨迹
错误：24.564公里为此车辆自12:00开始行驶的里程
应该为：从12:25开始记录里程数（或12:25后第一个可获得里程的数据开始）

**Comment by mqwangincar** [comment]
![screenshot_2015-03-19-23-05-39](https://cloud.githubusercontent.com/assets/9412266/6794158/5ed7404a-d209-11e4-935f-8218e6ddbfa4.jpeg)
这个是 正确的

**Comment by AceBear** [comment]
#### 需要修改下面的逻辑

$\incar\packages\maplocus\api\maplocusService.js
MaplocusService.prototype.getRecordStatistics

使用location数据中的精确里程数

``` SQL
SELECT L.tripId, L.travelDistance AS dist
    FROM t_account A
    JOIN t_car_user U ON U.s4_id = A.s4_id and U.acc_id = A.id and U.user_type = 1
    JOIN t_car C ON C.s4_id = U.s4_id and C.id = U.car_id
    JOIN t_pos_tracking P ON P.s4_id = C.s4_id and P.obd_code = C.obd_code
    JOIN t_obd_location L ON L.obdCode = P.obd_code
        and L.locationTime >= DATE_SUB(P.tm_start,INTERVAL 8 HOUR)
        and L.locationTime <= DATE_SUB(ifnull(P.tm_stop, now()),INTERVAL 8 HOUR)
WHERE A.wx_oid LIKE 'o-ElVtzzO2RH70kM6aqyIiFtnvNY%' and P.tracking_id = 4
ORDER BY L.locationTime ASC
```

**Comment by AceBear** [comment]
Fixed. 排除了第1点之前的里程值.
已发布.
