### ISSUE TITLE
汇总计算需求

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#155]
HP胡斌需要一些统计报表
现在只能通过读取每台车的单次行程数据,然后求和计算得到

他希望能有一个API接口,可以直接获取汇总后的结果:
某个时间段,对多个车辆的:行驶里程, 总油耗, 活动时间

报表示范
![default](https://cloud.githubusercontent.com/assets/5030312/6726680/18ffc130-ce55-11e4-8334-4abc70f7af1d.jpg)

**Comment by mqwangincar** [comment]
will not fix
