### ISSUE TITLE
发布流程制定

### ISSUE THREAD

**Issue by mqwangincar** [InCar/Track#16]
包括在发布内容识别，发布须提交的东西，时间点选择等

**Comment by mqwangincar** [comment]
What is the detial

王明青Mingqing Wang | InCar

发件人: XGH [mailto:notifications@github.com] 
发送时间: 2014年11月8日 11:44
收件人: InCar/Track
抄送: Wang Mingqing
主题: Re: [Track] 发布流程制定 (#16)

Closed #16 https://github.com/InCar/Track/issues/16 .

**Comment by AceBear** [comment]
更新了README.md
https://github.com/InCar/Track  
@InCar/c6
