### ISSUE TITLE
防盗报警过于频繁

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#169]
很多设备都有较为频繁的防盗报警(熄火后震动报警)

LD李工建议我们先监控一下这个报警,出现此报警时,马上联系车主,了解当时的现场环境
观察一段时间,了解情况后,再决定如何调整门限值

**Comment by mqwangincar** [comment]
OK. 你可以看看我的车、董世超的车、马涛的车。 每天出个报警的列表，包括报警时间，然后我去确认他们的车停在哪里了，有没有真的异常等
