### ISSUE TITLE
电子围栏

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#179]
百席地图上建立电子围栏
如果越出电子围栏,发出报警

**Comment by AceBear** [comment]
百度地图提供有一个 点是否在多边形内 的API
http://api.map.baidu.com/library/GeoUtils/1.2/docs/symbols/BMapLib.GeoUtils.html

自己写一个算法,也不复杂:从多边形内1点开始的射线,一定和多边形的边有奇数个交点(不含相切)

**Comment by mqwangincar** [comment]
FIXED
