### ISSUE TITLE
用车报告

### ISSUE THREAD

**Issue by mqwangincar** [InCar/Track#19]
1. 1号码没有产生10月下半月用车报告及10月用车报告
2. 1号没有收到10月用车报告推送

**Comment by AceBear** [comment]
这个问题的修正和MQS短信服务器混合在一起了,还没有提交到product上

**Comment by lahmyyc** [comment]
这一次因为定时器失效导致标签和用车报告都没有在11月1号重算，现在定时器已经修复了，我也已经手动重算了，不过推送给客户的用车报告因为过了时间所以就忽略了
