### ISSUE TITLE
轨迹回放对接

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#204]
需求：
1.车辆管理列表增加轨迹回放按钮
2.轨迹回放功能包含：按时间查询轨迹、轨迹可按加速倍回放、回放的轨迹按速度不同显示不用的轨迹颜色。界面请参考独立轨迹回放功能。

**Comment by septwong** [comment]
1.调用轨迹接口获取数据。已完成
2.实现功能的对接。2015-06-17
3.调整页面的布局。2015-06-18 上午

**Comment by septwong** [comment]
1.登录车队点击车辆管理，报length的错误。
2.倍数播放按钮样式。
3.轨迹播放完后，再重置，数据一块都为一片白。
4.第一查询路径显示在地图，重置后，在查询一个地图时，会出现多辆车。
5.查询某一辆车的路径后，在打开另一辆车的轨迹回放，地图会显示上一辆查询出的路径
6.引用icBaiduTrack.js需要用到fleetId.

**Comment by septwong** [comment]
2.已基本完成。
5.已完成。

**Comment by septwong** [comment]
1.已完成
