### ISSUE TITLE
资讯信息-修改功能有bug

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#205]
1.创建了一条带外部链接的资讯信息，进入修改页面，外部链接写入到了图文编辑器，且页面没有外部链接的功能。（改成修改和创建是保持一致的，且在修改的时候可以切换图文介绍或者使用外部链接）
2.没有上传图片也可以提交。（修改成不能）

**Comment by jiangli0509** [comment]
这个任务排在对接轨迹回放之前。

**Comment by septwong** [comment]
1.已完成，并在修改页面添加了活动类型供修改。
2.已完成，并修改了节油大赛和自驾游中的上传图片

**Comment by septwong** [comment]
补充：
1.根据发布类型修改title.已完成。
2.优化外部链接和活动介绍。已完成。
