### ISSUE TITLE
试乘试驾前台页面对接

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#216]

**Comment by septwong** [comment]
2015-07-13 
对接首页+搭建出ng-view的indexControl
2015-07-14
对接试驾：页面的输入显示；试乘试驾的获取和增加的api,简易的车辆，驾驶员的获取和试乘试驾的增加，
2015-07-15
对接试驾：完善车辆，试驾员的获取，改为获取可用的车辆，和试驾员；对接新出的两个html（首页，试驾）和css;完成试驾的添加的完整功能。

**Comment by septwong** [comment]
2015-07-16
试驾：完成了分页，搜索，查看，修改，结束试驾等操作（点击结束试驾后，会生成报告，由于没有api,先放置了）；
