### ISSUE TITLE
附近的加油站的地图

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#22]
客户反应,虽然知道了加油站的地址,但仍然不知道怎么去那里,希望能点击一下,给出一个路线图.
## 百度地图

[百度地图提供了此类API可以使用](http://developer.baidu.com/map/index.php?title=webapi/direction-api)
![百度路线图](http://developer.baidu.com/map/static/img/webservice-fn4.jpg)

**Comment by AceBear** [comment]
百度地图还提供了很多其它功能,供参考
http://developer.baidu.com/map/index.php?title=car

![baidu](https://cloud.githubusercontent.com/assets/5030312/4878672/d70e37d4-6315-11e4-8c08-884f7cdb30db.png)

**Comment by mqwangincar** [comment]
这个留给李磊吧，在做的时候就考虑了这个需求，但因为时间和担心地图加载的速度流量所以当时没做。 
@boyandnet 这次做轨迹记录时同时做了吧。 有两个地图，一个是搜索结束后，点击地图查看所有的加油站所在位置，另一个是在每个加油站信息旁放个地图图片点击后可以查看这个加油站
