### ISSUE TITLE
微信页面重新对接问题

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#220]

**Comment by jiangli0509** [comment]
1.服务预约中，新页面中没有此代码，如下图：
![image](https://cloud.githubusercontent.com/assets/5874912/9953887/3ceb08c8-5e17-11e5-95db-5586da1b1dde.png)  ---《已解决》

2.信息一览中，没有加载图标的代码  ---《已解决》
3.车辆报警中，新代码中没有
![image](https://cloud.githubusercontent.com/assets/5874912/9953900/51851918-5e17-11e5-81e4-be9c1a9995c1.png)      ---《已解决》
对接页面后出现，页面无任何显示，浏览器报出错误：
TypeError: n.height is not a function    ---《已解决》

4.活动详情中，不仅有活动的详情页面，还有如果没有参加活动可以报名的页面；此页面也无显示tips的提示框如（信息一览）  ---《已解决》

**Comment by dongliu1** [comment]
一、行车分析页面
问题1：新页面中日历一栏缺少查询按钮的代码，没有“w-b22”样式。
![_x ot blougbbzs p4nadty](https://cloud.githubusercontent.com/assets/13448811/9953830/d910f27c-5e16-11e5-891b-8803d3a4b501.png)     ---《已解决》

问题2：新页面中多出“最近一段行驶”一栏，没有对应的行驶数据。---《已解决》
问题3：新页面中速段统计多出一栏统计图表，且数据分段有四层，原页面只有三层，若采用原页面会改变显示方式，导致样式与新页面不同。---《已解决》
问题4：新页面缺少如下几段代码
![1](https://cloud.githubusercontent.com/assets/13448811/9954017/30052a3e-5e18-11e5-9cb1-4522f746997e.png)
![2](https://cloud.githubusercontent.com/assets/13448811/9954022/36b3810a-5e18-11e5-8845-33a9cdcbb5c6.png)  ---《已解决》

问题5：新页面底部多出返回按钮。---《已解决》
问题6：页面出现不了“饼状图”  ，报错误：TypeError: $(...).highcharts is not a function

**Comment by septwong** [comment]
资讯活动: 无法滑动加载，没有“icon-nodata”   ---《已解决》

**Comment by dongliu1** [comment]
二、行车手册页面
问题：新页面缺少一部分代码，如下：
![3](https://cloud.githubusercontent.com/assets/13448811/9954164/4830c626-5e19-11e5-95bf-b154fc5ed2ff.png)（已添加）

**Comment by dongliu1** [comment]
三、用车报告页面
周报、半月报、月报页面都缺少一行代码，如下：
![](https://cloud.githubusercontent.com/assets/13448811/9954017/30052a3e-5e18-11e5-9cb1-4522f746997e.png)
（已添加）

**Comment by septwong** [comment]
我的活动 ： 缺少tips and loading；活动加载有bug     TypeError: n.height is not a function   ---《已解决》

**Comment by dongliu1** [comment]
四、保养记录（myCar）页面
问题1：新页面中保养费用一项没有动态数据，隐藏这一项后，样式变化较大。---《已解决》（添加了保养费用着一项，并显示的数据）
问题2：新页面底部多出一个加载更多按钮，静态的。---《已解决》
问题3：新页面缺少无数据提示和加载代码。活动加载有bug TypeError: n.height is not a function ---《已解决》

**Comment by dongliu1** [comment]
五、保养建议（propose）页面
问题：新页面底部缺少“预约保养”按钮。---《已解决》

**Comment by septwong** [comment]
远程检测：活动加载有问题，直接进入历史页面多数会出现空白，并且在其他的滑动加载的页面也是一样会出现这样的问题。---《已解决》

**Comment by dongliu1** [comment]
车型介绍新页面中carType页面缺少一行代码，如下图中最后一行：
![1](https://cloud.githubusercontent.com/assets/13448811/9984752/1ccc2ed8-6050-11e5-85b5-4696a1ca45b8.png)
且缺少无数据提示代码
（已添加）

**Comment by dongliu1** [comment]
加油站详情页面中多出多行代码，没有hindebox，最下面多出加载更多代码（已删除，保持原有代码布局）

**Comment by dongliu1** [comment]
提示灯页面，新页面中多出一套图文，旧页面中没有清晰的图文显示。且，新页面中缺少没有数据提示语加载提示代码。（已解决，保持原页面不变）

**Comment by septwong** [comment]
轨迹记录 ：
1.点击跟多报错误：TypeError: n.height is not a function  ---《已解决》

**Comment by dongliu1** [comment]
我的信息页面，新页面中缺少弹出框代码。（已添加）

**Comment by Septemberwh** [comment]
保险计算器：
1.title显示错误

**Comment by dongliu1** [comment]
我的预约页面，缺少“拒绝理由”一栏和没有数据提示代码。（已添加）

**Comment by septwong** [comment]
信息一览：行车分析
![qq 20150922094508](https://cloud.githubusercontent.com/assets/9412495/10009519/b97e9462-6110-11e5-88ba-a9f55d9b2b39.png)

**Comment by septwong** [comment]
行车分析： 
![qq 20150922112557](https://cloud.githubusercontent.com/assets/9412495/10010427/e2182caa-611d-11e5-8407-ffb27be747c2.png)

**Comment by septwong** [comment]
轨迹记录 ：
1.title显示有错误  (已解决--jl)

保险计算器：
1.title显示错误 (已解决--jl)

引用的icHeader是引用的wx-site里面的
