### ISSUE TITLE
车型介绍

### ISSUE THREAD

**Issue by jiangli0509** [InCar/Track#4]
web和微站端实现车型介绍

**Comment by AceBear** [comment]
你可以在这里评论给别人 @boyandnet  @mqwangincar 
这样,他们也会收到提醒

**Comment by AceBear** [comment]
或者,你也可以这样提醒所有人 @InCar/c6

**Comment by AceBear** [comment]
@InCar/c6 ISSUE只有很简单的功能
每个ISSUE有一个标题,一些文字内容(或可以拖放进来一些图片)
ISSUE可以有 指派人Assignee, 里程碑milestore, 和 标签Labels属性

Assignee: 被指派给某个人,负责此ISSUE
milestore: 可以限制某个时间底线
Labels: 突出这个ISSUE的性质,比如,是BUG,还是新功能feature

**Comment by jiangli0509** [comment]
微站端的车型介绍已完成
