### ISSUE TITLE
简单轨迹呈现

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#60]
- 在 **更多**菜单页面里,增加一个菜单项 **行车轨迹**
- 点击 **行车轨迹** 链接到一个新页面
- 在 **行车轨迹** 页面, 嵌入 #51 行车轨迹控件
- 在 **行车轨迹** 页面, 调用 #52 取得轨迹数据
- 把从 #52 获取的数据 用 #51 来呈现

**Comment by AceBear** [comment]
这个完成以后,我们在这个基础上增加"按钮"来让用户控制记录与否

**Comment by AceBear** [comment]
@jiangli0509 
切换到 _pos-tracking_ 分支
直接用浏览器打开本地文件 _$\incar\packages\maplocus\test\test.html_ 看效果

你需要补全 _$\incar\packages\maplocus\html\icBaiduMap.js_ 第8行里的 `function drawPaths(map, paths)`

NOTE: 你原来的 **BMapLib** 在这里名称变为 **baiduCurveLineApi**
BTW: 完成后,把不需要文件删除掉.

**Comment by jiangli0509** [comment]
完成
