### ISSUE TITLE
Loading图标有时不消失

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#66]
所有采用ng-include的页面都有如下图所示Loading图标,有时不会消失的现象
![screenshot_2014-12-20-14-18-14](https://cloud.githubusercontent.com/assets/5030312/5513976/71ad7274-8854-11e4-9e1d-6959276676d8.png)
### 原因初步分析

更改为ng-include加载子视图是一个异步过程,
如果加载子视图的过程,比查询处理来得要慢,当么,当查询处理完成后,调用hide()方法时,子视图还没加载上.
### 解决方案:

在angularJS里,不到万不得已,不要使用jquery来处理DOM元素
要坚持使用angularJS的data-binding(比如ng-show, ng-hide directive)方式来控制DOM元素

**Comment by jiangli0509** [comment]
已完成，把所有页面的图标都用angularjs控制了
