### ISSUE TITLE
车队登录

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#74]
1. 修改数据库t_4s表,扩展一个字段biz_mode tinyint型,用来标识业务类型, 0-4S店 1-车队
2. 修改Service.Get4SById($\incar\web\wservice\motor\4S.ts) 方法, 返回新增加的字段
3. 修改页面$\incar\web\wsite\login.html, 当用户登录到一个车队时,重定向到车队扉页
4. "车队扉页"位于 **/fleet/index.html**

**特别注意COOKIES**
以前的业务,登录时储存了大量COOKIE,由于每次请求,所有的COOKIES都会被发往服务端,因此,这是一种低效的方案,用本地变量存储需要保存的变量,而不是用COOKIES

**Comment by jiangli0509** [comment]
已完成

**Comment by AceBear** [comment]
不是代码写完了就"已完成"了,实际在数据库中插入数据,试过了没有?

**Comment by jiangli0509** [comment]
测试过了的
