### ISSUE TITLE
API-创建车队

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#75]
实现一个API用来创建车队
POST /api/fleet

相关文档参见
http://dev.incardata.com.cn:7002/package/@incar/fleet

填充下面JS文件中的FleetAPI.post方法即可
$\incar\packages\fleet\api\FleetAPI.js

需要执行以下逻辑
1. 强制保证biz_mode=1 参见 #74 
2. 调用bizCore.Org中的方法完成向数据库添加车队的功能
3. 成功返回新创建的车队对象

**注意:严禁直接操作数据库,一定要使用bizCore和数据库进行交互**

**Comment by jiangli0509** [comment]
你给的测试用例的token解析出来权限不足，解析出来是我的id，不是管理员id啊

**Comment by jiangli0509** [comment]
已完成

**Comment by AceBear** [comment]
$\incar\packages\fleet\test\fleet.js 里,去掉decodeURIComponent的调用

``` javascript
"Cookie": "token="+decodeURIComponent("3yhl5V2NYwmomFasY8jvh7RmzYBPqiWV8lWYxGRcvDRl1Ay2TDd3eSmjZ6OdmmuobSbP%2Bb%2B8LCWcuk6443r0SA%3D%3D")+";" }
```
