### ISSUE TITLE
实现Org.GetOrgs方法

### ISSUE THREAD

**Issue by AceBear** [InCar/Track#77]
### biz-core.Org.GetOrgsG*(filter, pageSize, nextMarker, sortBy)

$\incar\packages\biz-core\lib\Org.js
Generator方法.获取所有的Org对象.
filter: 过滤条件, 如{ name: /s/i, biz_mode: 1 }, 代表返回所有name包含s(不区分大小写)且biz_mode等于1的对象.
如果过滤条件里是一个正则表达式,那么把属性转换为字符串,做字符串匹配;
如果过滤条件里不是正则表达式,那么直接比较值是否相等匹配.
pageSize: 可选.分页大小,默认不分页,返回全部.
nextMarker: 可选.填入上1页返回的最后一个org.id, 默认不填表示从第1页开始返回.
sortBy: 可选.排序属性,默认按id升序.如name-表示按name降序, id+或id表示按id升序.
return: { total: 34, orgs: [] }. total,符合过滤条件的对象总数;orgs,对象Org的数组
- 写至少一个测试用例
- 在README.md补充示范代码

**Comment by jiangli0509** [comment]
已完成

**Comment by AceBear** [comment]
缺测试用例
缺README.md示例代码.

**Comment by jiangli0509** [comment]
测试用例和README.md示例代码不是本来就已经有的吗？

**Comment by jiangli0509** [comment]
fleet/test/fleet.js的返回所有车队不是GetOrgsG的测试用例？

**Comment by AceBear** [comment]
fleet 是外围业务逻辑层
biz-core是核心业务逻辑层
这两者有一个分界线,各是各的

**Comment by AceBear** [comment]
- 此方法要求 获取所有的**Org对象**
- GetRowsCount应当放在内部, 如果是generator方法应该有G后缀, 名称上不应当出现rows这样的数据库概念
